# .air.toml
# Working directory
root = "."
tmp_dir = "tmp"

[build]
# What to run when files change
cmd = "go build -o ./tmp/main ."
# Binary that gets executed
bin = "tmp/main"
# Include sub-directories (except vendor)
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]

# Delay after file change before rebuilding (ms)
delay = 1000
kill_delay = 500

[log]
# Show timestamps in logs
time = true
